{"level":"error","message":"[indexSync] error fetch failed","name":"MeiliSearchCommunicationError","stack":"MeiliSearchCommunicationError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"[indexSync] error fetch failed","name":"MeiliSearchCommunicationError","stack":"MeiliSearchCommunicationError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"[indexSync] error fetch failed","name":"MeiliSearchCommunicationError","stack":"MeiliSearchCommunicationError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"[indexSync] error fetch failed","name":"MeiliSearchCommunicationError","stack":"MeiliSearchCommunicationError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"[indexSync] error fetch failed","name":"MeiliSearchCommunicationError","stack":"MeiliSearchCommunicationError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"[/ask/bingAI] Error handling BingAI response InvalidRequest: Request can't have PreviousMessages for an existing conversation.","stack":"Error: InvalidRequest: Request can't have PreviousMessages for an existing conversation.\n    at WebSocket.<anonymous> (file:///Users/0xborgil/Downloads/IntelliumGPT/node_modules/nodejs-gpt/src/BingAIClient.js:498:36)\n    at WebSocket.emit (node:events:527:35)\n    at Receiver.receiverOnMessage (/Users/0xborgil/Downloads/IntelliumGPT/node_modules/ws/lib/websocket.js:1209:20)\n    at Receiver.emit (node:events:515:28)\n    at /Users/0xborgil/Downloads/IntelliumGPT/node_modules/ws/lib/receiver.js:608:16\n    at node:internal/process/task_queues:140:7\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"[/ask/bingAI] Error handling BingAI response InvalidRequest: Request can't have PreviousMessages for an existing conversation.","stack":"Error: InvalidRequest: Request can't have PreviousMessages for an existing conversation.\n    at WebSocket.<anonymous> (file:///Users/0xborgil/Downloads/IntelliumGPT/node_modules/nodejs-gpt/src/BingAIClient.js:498:36)\n    at WebSocket.emit (node:events:527:35)\n    at Receiver.receiverOnMessage (/Users/0xborgil/Downloads/IntelliumGPT/node_modules/ws/lib/websocket.js:1209:20)\n    at Receiver.emit (node:events:515:28)\n    at /Users/0xborgil/Downloads/IntelliumGPT/node_modules/ws/lib/receiver.js:608:16\n    at node:internal/process/task_queues:140:7\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"[/ask/bingAI] Error handling BingAI response Cannot read properties of undefined (reading 'match')","stack":"TypeError: Cannot read properties of undefined (reading 'match')\n    at getCitations (/Users/0xborgil/Downloads/IntelliumGPT/api/server/utils/citations.js:10:54)\n    at handleText (/Users/0xborgil/Downloads/IntelliumGPT/api/server/utils/handleText.js:77:19)\n    at ask (/Users/0xborgil/Downloads/IntelliumGPT/api/server/routes/ask/bingAI.js:190:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /Users/0xborgil/Downloads/IntelliumGPT/api/server/routes/ask/bingAI.js:83:10"}
{"code":"ENOENT","errno":-2,"level":"error","message":"Error deleting file ENOENT: no such file or directory, unlink '/Users/0xborgil/Downloads/IntelliumGPT/client/public/images/64d4c8cb4209ab0c3de03169/thinkingemojic4dmodel000.webp'","path":"/Users/0xborgil/Downloads/IntelliumGPT/client/public/images/64d4c8cb4209ab0c3de03169/thinkingemojic4dmodel000.webp","stack":"Error: ENOENT: no such file or directory, unlink '/Users/0xborgil/Downloads/IntelliumGPT/client/public/images/64d4c8cb4209ab0c3de03169/thinkingemojic4dmodel000.webp'","syscall":"unlink"}
{"code":"ENOENT","errno":-2,"level":"error","message":"Error deleting file ENOENT: no such file or directory, unlink '/Users/0xborgil/Downloads/IntelliumGPT/client/public/images/64d4c8cb4209ab0c3de03169/thinkingemojic4dmodel000.webp'","path":"/Users/0xborgil/Downloads/IntelliumGPT/client/public/images/64d4c8cb4209ab0c3de03169/thinkingemojic4dmodel000.webp","stack":"Error: ENOENT: no such file or directory, unlink '/Users/0xborgil/Downloads/IntelliumGPT/client/public/images/64d4c8cb4209ab0c3de03169/thinkingemojic4dmodel000.webp'","syscall":"unlink"}
{"level":"error","message":"[/ask/bingAI] Error handling BingAI response InvalidRequest: Request can't have PreviousMessages for an existing conversation.","stack":"Error: InvalidRequest: Request can't have PreviousMessages for an existing conversation.\n    at WebSocket.<anonymous> (file:///Users/0xborgil/Downloads/IntelliumGPT/node_modules/nodejs-gpt/src/BingAIClient.js:498:36)\n    at WebSocket.emit (node:events:527:35)\n    at Receiver.receiverOnMessage (/Users/0xborgil/Downloads/IntelliumGPT/node_modules/ws/lib/websocket.js:1209:20)\n    at Receiver.emit (node:events:515:28)\n    at /Users/0xborgil/Downloads/IntelliumGPT/node_modules/ws/lib/receiver.js:608:16\n    at node:internal/process/task_queues:140:7\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"[/ask/bingAI] Error handling BingAI response InvalidRequest: Request can't have PreviousMessages for an existing conversation.","stack":"Error: InvalidRequest: Request can't have PreviousMessages for an existing conversation.\n    at WebSocket.<anonymous> (file:///Users/0xborgil/Downloads/IntelliumGPT/node_modules/nodejs-gpt/src/BingAIClient.js:498:36)\n    at WebSocket.emit (node:events:527:35)\n    at Receiver.receiverOnMessage (/Users/0xborgil/Downloads/IntelliumGPT/node_modules/ws/lib/websocket.js:1209:20)\n    at Receiver.emit (node:events:515:28)\n    at /Users/0xborgil/Downloads/IntelliumGPT/node_modules/ws/lib/receiver.js:608:16\n    at node:internal/process/task_queues:140:7\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"[indexSync] error fetch failed","name":"MeiliSearchCommunicationError","stack":"MeiliSearchCommunicationError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"[indexSync] error fetch failed","name":"MeiliSearchCommunicationError","stack":"MeiliSearchCommunicationError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"[indexSync] error fetch failed","name":"MeiliSearchCommunicationError","stack":"MeiliSearchCommunicationError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"[indexSync] error fetch failed","name":"MeiliSearchCommunicationError","stack":"MeiliSearchCommunicationError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error","message":"[indexSync] error fetch failed","name":"MeiliSearchCommunicationError","stack":"MeiliSearchCommunicationError: fetch failed\n    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
